### ISSUE TITLE
ts 调整

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/jet-scaffolds#31]
- [x] 禁止使用 `any`

**Comment by fahchen** [comment]
贴一下对应的 commit

**Comment by shaddollxz** [comment]
添加了严格模式显示隐式的 any ，显示申明的 any 在 eslint 里加的
https://github.com/Byzanteam/jet-linter/pull/33/commits/e10eff218d646111f7fd90e29f26bc2ec6b81997

**Comment by shaddollxz** [comment]
> 添加了严格模式显示隐式的 any ，显示申明的 any 在 eslint 里加的 [Byzanteam/jet-linter@e10eff2](https://github.com/Byzanteam/jet-linter/commit/e10eff218d646111f7fd90e29f26bc2ec6b81997)

这个是 tsconfig 的，刚才回复是 eslint 的（刚才按错了
https://github.com/Byzanteam/jet-linter/pull/21/commits/dabea70186946f7d2455769a15537932dd0a3643
